#**Non Graded Chalengge 5**
---


> Nama : Amrullah Pasadi

> Batch : RMT-020


---





##**A. Instruction**

- Buatlah Tensor dibawah ini dengan Python:
  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$
- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix} $$


##**B.Answer**

Import library yang dibutuhkan

In [2]:
import numpy as np
import pandas as pd

**Problem 1**  
Buatlah Tensor dibawah ini dengan Python:
  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

Deskripsikan vektor

In [14]:
A = [[[23,50],
      [7,12],
      [75,21],
      [57,12]],

     [[57,67],
      [99,43],
      [87,26],
      [18,84]]]

Ten_A = np.array(A)
print(Ten_A,'\n',type(Ten_A))

[[[23 50]
  [ 7 12]
  [75 21]
  [57 12]]

 [[57 67]
  [99 43]
  [87 26]
  [18 84]]] 
 <class 'numpy.ndarray'>


**Problem 2**

Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  B=
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

Defenisikan vektor

In [18]:
A = [[23,50,19],
     [7,12,109],
     [57,67,98]]
mat_A = np.array(A)
B =  [17,22,19]
mat_B = np.array(B)

print("perkalian waist : \n", mat_A * mat_B,'\n')
print("perkalian dot product : \n",mat_A @ mat_B)

perkalian waist : 
 [[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]] 

perkalian dot product : 
 [1852 2454 4305]


**Problem 3**

Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix} $$


In [20]:
V=[[23,50,19],
   [7,12,109],
   [57,67,98]]
TDI = np.array(V)

print(TDI,'\n',type(TDI))

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]] 
 <class 'numpy.ndarray'>


In [21]:
TDI.T #menTranpose matrix  

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [23]:
np.linalg.det(TDI) #hitung Determinan

131344.0000000002

In [25]:
np.linalg.inv(TDI) #Invers matrix TDI

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])